Botão de adicionar no fluxo mais chamativo
fga-eps-mds/2022-2-CAPJu-Interface pull request #34
Opened 2022-11-27 19:04 UTC by LucasLopesFrazao

Botão de adicionar no fluxo mais chamativo

## Issue 
resolve #19 

## Descrição
Anteriormente o botão de adicionar não estava intuitivo (mesmo cor do input(cinza claro) e estava como <span>).
Neste PR foi modificado este botão para deixar mais intuitivo para o usúario que realmente é um botão, transformando a tag para um <button> e modificando o CSS.

## Screenshots (se apropriado):
![image](https://user-images.githubusercontent.com/89523373/204154505-42d2aeab-27e7-41bc-9e71-acbccc77334a.png)
![image](https://user-images.githubusercontent.com/89523373/204154533-2507e23a-6f8e-4c0c-a624-42f41a966d9b.png)

## Tipos de Mudanças

- [ ] Bug fix (alteração ininterrupta que corrige um problema)
- [ ] Nova feature (mudança ininterrupta que adiciona funcionalidade)
- [ ] Breaking change (correção ou recurso que faria com que a funcionalidade existente não funcionasse como esperado)
- [ ] Documentação (adição ou remoção de algum artefato)
- [x] Refatoração

## Checklist:

- [x] Meu código segue os padrões de estilo deste projeto.
- [ ] Minha alteração requer uma alteração na documentação.
- [ ] Atualizei a documentação de acordo.

2022-11-28 17:50 UTC, ilus1 requested changes

2022-11-28 17:50 UTC, ilus1 commented on src/components/ButtonAdd/ButtonAdd.jsx
> +function ButtonAdd({ onClickProps }) {
A gente precisa pensar em um nome melhor pra esse componente :upside_down_face:

2022-11-28 17:50 UTC, ilus1 commented on src/pages/Flows/Flows.jsx
> +                    <button className="add-button-flow">Adicionar</button>
Acho q faltou trocar esse

2022-11-29 22:09 UTC, ilus1 approved these changes
Lembrete pra gente pensar em um nome melhor pro componente

2022-11-29 22:13 UTC, AntonioAldisio approved these changes
👍

2022-11-29 22:13 UTC, merged