12-corrigindo listagem de admins
fga-eps-mds/2022-2-CAPJu-Interface pull request #47
Opened 2022-12-02 23:02 UTC by SamuelGSouza

Correção da listagem de administradores da Unidade

## Issue #
Closes #11 #12 

## Descrição
Resolvido listagem incorreta de administradores de uma unidade.

## Tipos de Mudanças

- [x] Bug fix (alteração ininterrupta que corrige um problema)
- [ ] Nova feature (mudança ininterrupta que adiciona funcionalidade)
- [x] Breaking change (correção ou recurso que faria com que a funcionalidade existente não funcionasse como esperado)
- [ ] Documentação (adição ou remoção de algum artefato)

## Checklist:

- [x] Meu código segue os padrões de estilo deste projeto.
- [ ] Minha alteração requer uma alteração na documentação.
- [ ] Atualizei a documentação de acordo.

2022-12-02 23:03 UTC, ilus1 approved these changes
:+1:

2022-12-05 06:20 UTC, vitorAlves7 requested changes

2022-12-05 06:20 UTC, vitorAlves7 commented on src/pages/Unidades/Unidades.jsx
> +    console.log(unity._id);
Remover esse log aqui

2022-12-06 11:29 UTC, ilus1 approved these changes
:+1:

2022-12-06 11:29 UTC, merged