Controle da visualização das opções do sistema através do perfil
fga-eps-mds/2022-2-CAPJu-Interface pull request #67
Opened 2023-01-17 18:21 UTC by chaydson

#  Controle da visualização das opções do sistema através do perfil

## Issue 
Resolve https://github.com/fga-eps-mds/2022-2-CAPJu-Doc/issues/93

## Descrição
Seguindo as permissões mapeadas na planilha https://bit.ly/3CIoxmz foi implementada a verificação e controle de acesso as funcionalidades do sistema baseado no perfil do usuário.

## Screenshots:
![pr](https://user-images.githubusercontent.com/90580219/212979291-80d066e0-fc5f-4066-ae51-0e12a1cf059e.png)

## Tipos de Mudanças

- [ ] Bug fix (alteração ininterrupta que corrige um problema)
- [ ] Nova feature (mudança ininterrupta que adiciona funcionalidade)
- [ ] Breaking change (correção ou recurso que faria com que a funcionalidade existente não funcionasse como esperado)
- [ ] Documentação (adição ou remoção de algum artefato)
- [ ] Refatoração para melhoramento do código

## Checklist:

- [ ] Meu código segue os padrões de estilo deste projeto.
- [ ] Minha alteração requer uma alteração na documentação.
- [ ] Atualizei a documentação de acordo

2023-01-26 02:43 UTC, ilus1 requested changes

2023-01-26 02:43 UTC, ilus1 commented on src/pages/Processes/Processes.jsx
>          }}
poe isso aqui na mesma linha.
ex: {() => openEditModal(false)}

2023-01-26 02:43 UTC, ilus1 commented on src/__tests__/test_units.js
> +import { Permissions } from 'util/permissionChecker';
parece que alguns testes dessa classe meio q sumiram. Precisa dar uma olhada. Se não me engano ela tinha cobertira maior antes.

2023-01-26 02:53 UTC, SamuelGSouza commented on src/pages/Processes/Processes.jsx
>          }}
:+1:

2023-01-27 01:24 UTC, ilus1 approved these changes
:+1:

2023-01-27 01:26 UTC, merged